import type { LucideIcon } from "lucide-react";
import { BarChart3, BookOpen, CalendarDays, CircleDollarSign, FileImage, HeartHandshake, Plus, Settings, ShieldCheck, Users } from "lucide-react";

const sections: Record<string, { title: string; description: string; icon: LucideIcon; rows: string[][]; columns: string[] }> = {
  campaigns: { title: "Campaigns", description: "Create, fund, publish, and close campaign work.", icon: HeartHandshake, columns: ["Campaign", "Owner", "Raised", "Status"], rows: [["Clean water, powered by sunlight", "Neha Rao", "₹36.4L", "Active"], ["Learning labs beyond the last mile", "Arjun Bedi", "₹22.8L", "Active"], ["Women growing climate-ready farms", "Nila Joseph", "₹18.2L", "Active"], ["Assam flood response", "Imran Ali", "₹14.7L", "Urgent"]] },
  donations: { title: "Donations", description: "Reconcile payments, receipts, refunds, and donor intent.", icon: CircleDollarSign, columns: ["Reference", "Donor", "Amount", "Status"], rows: [["DON-98241", "Aarav Sharma", "₹5,000", "Settled"], ["DON-98240", "Anonymous", "₹1,200", "Settled"], ["DON-98239", "Maya Iyer", "₹12,000", "Settled"], ["DON-98238", "Kabir Mehta", "₹2,500", "Review"]] },
  users: { title: "People", description: "Supporters, participants, staff accounts, and consent records.", icon: Users, columns: ["Person", "Relationship", "Last active", "Status"], rows: [["Ananya Kapoor", "Monthly donor", "Today", "Active"], ["Ravi Menon", "Partner lead", "Yesterday", "Active"], ["Saira Begum", "Volunteer", "2 days ago", "Active"], ["Thomas Lee", "Donor", "4 days ago", "Active"]] },
  volunteers: { title: "Volunteers", description: "Applications, safeguarding checks, matching, and hours.", icon: ShieldCheck, columns: ["Applicant", "Role", "Location", "Stage"], rows: [["Diya Shah", "STEM mentor", "Remote", "Interview"], ["Aditya Rao", "Field photographer", "Bengaluru", "Screening"], ["Rhea Thomas", "Data analyst", "Remote", "Matched"], ["Mohit Sen", "Relief roster", "Guwahati", "Cleared"]] },
  events: { title: "Events", description: "Registration, attendance, capacity, and follow-up.", icon: CalendarDays, columns: ["Event", "Date", "Registered", "Status"], rows: [["Field Notes: Rebuilding", "18 Aug", "386", "Open"], ["Bengaluru Open House", "6 Sep", "112", "Open"], ["The Long Table", "21 Sep", "84", "Open"], ["Monsoon Briefing", "11 Jul", "620", "Complete"]] },
  stories: { title: "Stories & blog", description: "Consent-aware publishing from draft through review.", icon: BookOpen, columns: ["Story", "Author", "Updated", "Stage"], rows: [["Kavya’s lab stays open", "Leena D’Souza", "Today", "Published"], ["Water committee, year two", "Aman Qureshi", "Yesterday", "Review"], ["Seeds after the landslide", "Mia George", "3 days", "Draft"], ["What verification looks like", "Farah Khan", "6 days", "Published"]] },
  media: { title: "Media library", description: "Rights-managed imagery, video, transcripts, and documents.", icon: FileImage, columns: ["Asset", "Collection", "Rights", "Updated"], rows: [["Water station opening", "Jal Jyoti", "Approved", "Today"], ["Learning lab workshop", "Shiksha Setu", "Approved", "Yesterday"], ["Wayanad seedlings", "Udaan", "Approved", "3 days"], ["FY26 annual report", "Governance", "Public", "8 days"]] },
  analytics: { title: "Analytics", description: "Acquisition, conversion, retention, and program engagement.", icon: BarChart3, columns: ["Metric", "Current", "Previous", "Change"], rows: [["Donation conversion", "4.8%", "4.1%", "+17%"], ["Monthly retention", "87.6%", "85.5%", "+2.1pt"], ["Volunteer completion", "62%", "58%", "+4pt"], ["Newsletter engagement", "48.3%", "46.9%", "+1.4pt"]] },
  settings: { title: "Settings", description: "Organization, roles, integrations, SEO, and notification defaults.", icon: Settings, columns: ["Area", "Owner", "Last reviewed", "Status"], rows: [["Organization profile", "Admin", "31 Jul", "Complete"], ["Payment integrations", "Finance", "1 Aug", "Connected"], ["Role management", "Security", "24 Jul", "Complete"], ["SEO defaults", "Comms", "2 Aug", "Complete"]] },
};

export default async function AdminSectionPage({ params }: { params: Promise<{ section: string }> }) {
  const { section } = await params;
  const data = sections[section] ?? sections.campaigns;
  const Icon = data.icon;
  return (
    <div className="mx-auto max-w-[1400px]">
      <header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><span className="grid size-11 place-items-center rounded-2xl bg-forest/10 text-forest"><Icon className="size-5" /></span><h1 className="mt-5 font-display text-4xl font-bold tracking-tight">{data.title}</h1><p className="mt-2 text-sm text-ink/45">{data.description}</p></div><button type="button" className="button-primary min-h-11"><Plus className="size-4" /> Add new</button></header>
      <section className="mt-8 overflow-hidden rounded-3xl border border-ink/8 bg-white shadow-[0_12px_35px_rgba(15,50,43,.05)] dark:bg-white/[0.055]">
        <div className="flex items-center justify-between border-b border-ink/8 p-5 sm:px-7"><p className="text-sm font-bold">Recent records</p><button type="button" className="text-xs font-bold text-forest">Export CSV</button></div>
        <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead><tr className="border-b border-ink/8 bg-ink/[0.025]">{data.columns.map((column) => <th key={column} scope="col" className="px-7 py-3 text-[0.62rem] font-extrabold uppercase tracking-[0.14em] text-ink/38">{column}</th>)}</tr></thead><tbody>{data.rows.map((row) => <tr key={row[0]} className="border-b border-ink/7 last:border-0 hover:bg-forest/[0.025]">{row.map((cell, index) => <td key={cell} className={`px-7 py-4 text-sm ${index === 0 ? "font-bold" : "text-ink/52"}`}>{index === row.length - 1 ? <span className="rounded-full bg-forest/[0.08] px-2.5 py-1 text-[0.65rem] font-bold text-forest">{cell}</span> : cell}</td>)}</tr>)}</tbody></table></div>
      </section>
    </div>
  );
}
