import type { Metadata } from "next";
import { ArrowDownToLine, BadgeCheck, FileCheck2, LockKeyhole, ShieldCheck } from "lucide-react";
import Link from "next/link";

import { recognitions, trustMarkers } from "@/content/site";

export const metadata: Metadata = { title: "Governance & accountability", description: "Ashaaya Foundation's governance, audited reporting, safeguarding commitments, and fund allocation." };

export default function GovernancePage() {
  return (
    <main><section className="border-b border-ink/10 bg-[#e7eee8] pb-20 pt-36 dark:bg-[#10251f]"><div className="page-shell"><p className="eyebrow">Governance & accountability</p><h1 className="display-title mt-6 max-w-5xl">Trust is a practice, not a badge.</h1><p className="prose-premium mt-6 max-w-2xl">Clear authority, independent oversight, published evidence, strong safeguarding, and a direct route to raise concerns.</p></div></section>
      <section className="section-space page-shell"><div className="grid gap-5 md:grid-cols-2">{trustMarkers.map((marker, index) => { const Icon = [FileCheck2, BadgeCheck, ShieldCheck, LockKeyhole][index] ?? ShieldCheck; return <article key={marker.title} className="rounded-4xl border border-ink/10 bg-paper p-7 shadow-soft sm:p-9"><span className="grid size-12 place-items-center rounded-2xl bg-forest/10 text-forest"><Icon className="size-5" /></span><h2 className="mt-7 font-display text-2xl font-bold">{marker.title}</h2><p className="mt-3 text-sm leading-7 text-ink/55">{marker.detail}</p></article>; })}</div></section>
      <section id="fund-allocation" className="scroll-mt-28 bg-[#0b3028] py-20 text-white sm:py-28"><div className="page-shell grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.19em] text-[#70d5b3]">FY 2025–26 allocation</p><h2 className="mt-5 font-display text-5xl font-semibold tracking-[-0.05em]">Every ₹100, accounted for.</h2><p className="mt-5 text-base leading-8 text-white/55">Audited expenditure, including field monitoring within program delivery.</p></div><div className="grid gap-4 sm:grid-cols-3">{[["₹91", "Program delivery", "Field teams, partners, materials, monitoring"], ["₹5", "Fundraising", "Donor care, payment costs, responsible growth"], ["₹4", "Governance", "Audit, board, compliance, secure systems"]].map(([value, label, detail]) => <div key={label} className="rounded-3xl border border-white/10 bg-white/[0.06] p-6"><p className="font-display text-4xl font-bold text-[#f3bd67]">{value}</p><h3 className="mt-4 font-bold">{label}</h3><p className="mt-2 text-xs leading-5 text-white/42">{detail}</p></div>)}</div></div></section>
      <section id="reports" className="scroll-mt-28 section-space page-shell"><div className="grid gap-10 lg:grid-cols-[1fr_1.2fr]"><div><p className="eyebrow">Reports & policies</p><h2 className="display-title mt-6">Open by default.</h2><p className="prose-premium mt-6">Request an accessible copy of any signed report or policy. Donor care sends the current board-approved document within one working day.</p></div><div className="divide-y divide-ink/10 border-y border-ink/10">{["Annual report 2025–26", "Audited financial statements 2025–26", "Safeguarding and participant protection policy", "Whistleblower and grievance policy", "Data privacy and retention schedule"].map((document) => <Link key={document} href="/contact?subject=Impact report" className="group flex items-center justify-between gap-5 py-5 font-bold"><span>{document}</span><ArrowDownToLine className="size-4 text-forest transition group-hover:translate-y-0.5" /></Link>)}</div></div></section>
      <section id="safeguarding" className="scroll-mt-28 page-shell pb-24"><div className="rounded-4xl bg-[#f0c16d] p-7 text-[#17231f] sm:p-10"><ShieldCheck className="size-7" /><h2 className="mt-6 font-display text-3xl font-bold">Raise a safeguarding concern securely.</h2><p className="mt-4 max-w-2xl text-sm leading-7 opacity-65">Reports go directly to the safeguarding lead and board-designated reviewer. Retaliation is prohibited, and anonymous reports can be made.</p><Link href="/contact?subject=Safeguarding concern" className="mt-6 inline-flex min-h-11 items-center rounded-full bg-[#102d26] px-5 text-sm font-bold text-white">Contact safeguarding</Link></div></section>
      <section className="border-t border-ink/10 py-16"><div className="page-shell"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-forest">Recognition</p><div className="mt-7 grid gap-4 md:grid-cols-3">{recognitions.map((recognition) => <article key={recognition.title} className="rounded-3xl border border-ink/10 p-6"><p className="text-xs font-bold text-forest">{recognition.year}</p><h2 className="mt-3 font-display text-xl font-bold">{recognition.title}</h2><p className="mt-1 text-xs text-ink/40">{recognition.issuer}</p><p className="mt-4 text-sm leading-6 text-ink/55">{recognition.description}</p></article>)}</div></div></section>
    </main>
  );
}
